baseURL = "https://nenimein.fi/"
languageCode = "en-us"
title = "Nieminen"
theme = ["hackerman", "matomo"]
pagination.pagerSize = 10
enableRobotsTXT = true

copyright = "Copyright © Sami Nieminen"

[imaging]
	quality = 80

[params]
  tagline = "// init blog.sh --mode=hackerman"
  author = "Sami Nieminen"
  authorEmail = "imas@nenimein.fi"
  authorNote = "Hacking away at motorcycles, cars, Azure and Linux."
  authorPhoto = "/img/me.jpg"
  mastodon = "https://mastodon.social/@celeroncool"

  github    = "https://github.com/yourusername"
  bitbucket = "https://bitbucket.org/yourusername"
  linkedin  = "https://linkedin.com/in/yourusername"
  instagram = "https://instagram.com/yourusername"
  keybase   = "https://keybase.io/yourusername"

[params.matomo]
	url = "https://matomo.nenimein.fi"
	id = 1

[params.matomo.track]
	button = "Allow tracking"
	message = "Allow me to track your page visit to my personal Matomo instance."
[params.matomo.block]
	button = "Disallow tracking"
	message = "You are **not** tracked."

[taxonomies]
  tag = 'tags'